In [2]:
import numpy as np
R = np.arange(1,10).reshape(3,3)
t = np.asarray([1,1,1]).reshape(3,1)
f = np.hstack([R,t])
f

array([[1, 2, 3, 1],
       [4, 5, 6, 1],
       [7, 8, 9, 1]])

In [3]:
k = np.vstack((f, [0,0,0,1]))
k

array([[1, 2, 3, 1],
       [4, 5, 6, 1],
       [7, 8, 9, 1],
       [0, 0, 0, 1]])

In [4]:
x = np.asarray([1, 2, 3, 4])
filt = np.asarray([True, False, True, False])
x[filt] = 5
x

array([5, 2, 5, 4])

In [5]:
x = np.arange(27).reshape(3,3,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [6]:
import tensorflow as tf

/home/jlurobot/anaconda3/envs/point/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/jlurobot/anaconda3/envs/point/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/jlurobot/anaconda3/envs/point/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/jlurobot/anaconda3/envs/point/lib/pyt

In [7]:
y = tf.reduce_max(x, axis=1)
#with tf.Session() as sess: sess.run(y.eval())

In [8]:
pad = (1,1,1)
temp = np.array(pad)
temp = np.lib.pad(temp, (1,1), 'constant', constant_values=(0,0))
temp

array([0, 1, 1, 1, 0])

In [9]:
padding = (np.array(temp)).repeat(2).reshape(5, 2)
padding

array([[0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0]])

In [10]:
input = np.ones(shape=(3,10,200, 240, 128))
pad = tf.pad(input, padding, "CONSTANT")
pad.shape

TensorShape([Dimension(3), Dimension(12), Dimension(202), Dimension(242), Dimension(128)])

In [12]:
coordinate = np.ones((2,2))
x = np.pad(coordinate, ((0, 0), (1, 0)), mode="constant", constant_values=2)
x

array([[2., 1., 1.],
       [2., 1., 1.]])

In [1]:
car = [1, 2, 3]
walker = [4, 5]
person = [car, walker]
person

[[1, 2, 3], [4, 5]]

In [2]:
import random
for i in range(10):
    print(random.random())

0.553810150359421
0.6781441699699248
0.9005987828301372
0.3794356131948694
0.34813358786215665
0.18749080375599048
0.49545489152241295
0.22771390875646624
0.37913837022851293
0.2608258409300366
